import os
import argparse
import sys

def find_gitignores(start_path):
    """Recursively finds all .gitignore files starting from start_path."""
    gitignore_files = []
    for root, dirs, files in os.walk(start_path, topdown=True, followlinks=True):
        # Skip .git directories
        dirs[:] = [d for d in dirs if d != '.git']
        if '.gitignore' in files:
            gitignore_files.append(os.path.join(root, '.gitignore'))
    return gitignore_files

def process_gitignore(file_path, root_path):
    """Reads a .gitignore file, processes patterns, and prepends relative paths."""
    processed_patterns = []
    rel_dir = os.path.dirname(os.path.relpath(file_path, root_path))
    try:
        with open(file_path, 'r') as f:
            for line in f:
                stripped_line = line.strip()
                # Ignore comments and empty lines
                if stripped_line and not stripped_line.startswith('#'):
                    # Prepend the relative directory path to the pattern
                    # Handle patterns starting with '/' (relative to .gitignore location)
                    if stripped_line.startswith('/'):
                         # Keep it relative to the source .gitignore's directory
                         pattern_path = os.path.join(rel_dir, stripped_line[1:])
                    # Handle patterns starting with '!' (negation) - keep the '!'
                    elif stripped_line.startswith('!'):
                         negation = '!'
                         pattern = stripped_line[1:]
                         if pattern.startswith('/'):
                             pattern_path = negation + os.path.join(rel_dir, pattern[1:])
                         else:
                             # Non-rooted patterns apply within the source dir and below
                             # For simplicity, we prepend the dir path.
                             # More complex logic might be needed for full gitignore spec compliance.
                             pattern_path = negation + os.path.join(rel_dir, pattern)
                    else:
                         # Regular pattern
                         pattern_path = os.path.join(rel_dir, stripped_line)

                    # Normalize path separators for consistency
                    processed_patterns.append(pattern_path.replace(os.path.sep, '/'))
    except Exception as e:
        print(f"Error reading {file_path}: {e}", file=sys.stderr)
    return processed_patterns

def main():
    parser = argparse.ArgumentParser(description="Aggregate .gitignore files recursively, prepending relative paths.")
    parser.add_argument("path", nargs='?', default=".", help="Directory to start searching from (default: current directory).")
    args = parser.parse_args()

    start_dir = os.path.abspath(args.path)
    root_gitignore_path = os.path.join(os.getcwd(), '.gitignore') # Target is always CWD's .gitignore

    print(f"Starting search in: {start_dir}")
    print(f"Target root .gitignore: {root_gitignore_path}")

    gitignore_files = find_gitignores(start_dir)

    if not gitignore_files:
        print("No .gitignore files found.")
        return

    print(f"Found {len(gitignore_files)} .gitignore files.")

    output_lines = ["\n# --- START AGGREGATED GITIGNORE (Generated by script) ---"]

    for file_path in gitignore_files:
        # Skip the root gitignore itself if found within the search path
        if os.path.abspath(file_path) == os.path.abspath(root_gitignore_path):
             print(f"Skipping root gitignore: {file_path}")
             continue
             
        source_rel_path = os.path.relpath(file_path, os.getcwd()).replace(os.path.sep, '/')
        output_lines.append(f"\n# Source: {source_rel_path}")
        patterns = process_gitignore(file_path, os.getcwd())
        if patterns:
            output_lines.extend(patterns)
        else:
            output_lines.append("# (No valid patterns found)")


    output_lines.append("# --- END AGGREGATED GITIGNORE ---")

    try:
        with open(root_gitignore_path, 'a') as f:
            f.write("\n".join(output_lines))
            f.write("\n") # Add a trailing newline
        print(f"Successfully appended aggregated patterns to: {root_gitignore_path}")
        print(f"Processed {len(gitignore_files)} .gitignore files.")
    except Exception as e:
        print(f"Error writing to {root_gitignore_path}: {e}", file=sys.stderr)

if __name__ == "__main__":
    main()
